/**
 * compliance.ts — Compliance module types
 * RCM entries, TDS deductions, Advances, Challans
 * [JWT] Replace with GET/POST /api/compliance/*
 */

export interface RCMEntry {
  id: string;
  voucher_id: string;
  voucher_no: string;
  entity_id: string;
  date: string;
  party_name: string;
  party_gstin: string;
  rcm_section: "section_9_3" | "section_9_4";
  taxable_value: number;
  cgst_amount: number;
  sgst_amount: number;
  igst_amount: number;
  cess_amount: number;
  status: "open" | "posted" | "cancelled";
  rcm_jv_id?: string;
  rcm_jv_no?: string;
  posted_at?: string;
  cancelled_at?: string;
  cancel_reason?: string;
  created_at: string;
}

export const rcmEntriesKey = (e: string) => `erp_rcm_entries_${e}`;

// ── Advance Entry (vendor payment advances + customer receipt advances) ──
export interface AdvanceAdjustment {
  invoice_id: string; invoice_no: string;
  amount_adjusted: number; tds_adjusted: number; date: string;
}
export interface AdvanceEntry {
  id: string; advance_ref_no: string; // ADVP/FY/0001 or ADVR/FY/0001
  entity_id: string;
  party_type: "vendor" | "customer";
  party_id: string; party_name: string;
  date: string;
  source_voucher_id: string; source_voucher_no: string;
  po_ref?: string;      // linked PO number if advance is against a PO
  so_ref?: string;      // linked SO number if advance is against a SO
  advance_amount: number;   // gross advance
  tds_amount: number;       // TDS deducted on advance (0 if N/A)
  net_amount: number;       // actual bank outflow/inflow
  adjustments: AdvanceAdjustment[];
  balance_amount: number;   // advance_amount - sum(adjustments.amount_adjusted)
  tds_balance: number;      // tds_amount - sum(adjustments.tds_adjusted)
  status: "open" | "partial" | "adjusted" | "cancelled";
  tds_status: "na" | "deducted_inline" | "pending_journal" | "journal_posted";
  tds_jv_id?: string; tds_jv_no?: string;
  created_at: string; updated_at: string;
}
export const advancesKey = (e: string) => `erp_advances_${e}`;

// ── TDS Deduction Register (one entry per TDS event) ──────────────────
export interface TDSDeductionEntry {
  id: string; entity_id: string;
  source_voucher_id: string; source_voucher_no: string;
  source_voucher_type: "Purchase" | "Payment" | "Journal";
  party_id: string; party_name: string; party_pan: string;
  deductee_type: "individual" | "company" | "huf" | "no_pan";
  tds_section: string; nature_of_payment: string;
  tds_rate: number;
  gross_amount: number;
  advance_tds_already: number; // advance TDS deducted earlier for same invoice
  net_tds_amount: number;      // gross TDS - advance_tds_already
  date: string;
  quarter: "Q1" | "Q2" | "Q3" | "Q4";
  assessment_year: string;     // "2026-27"
  advance_ref?: string;        // links to AdvanceEntry.advance_ref_no if advance
  tds_jv_id?: string; tds_jv_no?: string;
  challan_id?: string;         // set when challan deposited
  status: "open" | "posted" | "cancelled";
  created_at: string;
}
export const tdsDeductionsKey = (e: string) => `erp_tds_deductions_${e}`;

// ── Expanded ChallanEntry ─────────────────────────────────────────────
export interface ChallanEntry {
  id: string; entity_id: string;
  challan_no: string; bsr_code: string;
  cin_no: string; // Challan Identification Number (generated by bank)
  bank_name: string;
  date: string;
  major_head: "0020" | "0021"; // 0020=Company, 0021=Non-company
  minor_head: "200" | "400"; // 200=TDS payable, 400=regular assessment
  tds_section: string; // primary section this challan covers
  amount: number;
  interest: number; // interest for late deposit
  penalty: number;
  assessment_year: string; // "2026-27"
  quarter: "Q1" | "Q2" | "Q3" | "Q4";
  period_from: string; period_to: string;
  covered_deduction_ids: string[]; // TDSDeductionEntry IDs covered by challan
  status: "pending" | "paid";
  created_at: string; updated_at: string;
}
export const challansKey = (e: string) => `erp_tds_challan_${e}`;

// ── TDS Receivable Entry (Form 26AS — income-side TDS) ────────────────
export interface TDSReceivableEntry {
  id: string; entity_id: string;
  voucher_id: string;             // Receipt or Journal voucher that captured this
  voucher_no: string;
  customer_id: string; customer_name: string;
  customer_pan: string;
  customer_tan: string;           // customer's TAN — key for 26AS matching
  tds_section: string;            // 194J, 194C, 194A etc.
  invoice_ref: string;            // bill reference from receipt bill allocation
  invoice_date: string;
  amount_received: number;        // gross amount (what customer should have paid)
  tds_amount: number;             // TDS deducted by customer
  net_received: number;           // bank inflow = amount_received - tds_amount
  date: string;
  quarter: "Q1"|"Q2"|"Q3"|"Q4";
  assessment_year: string;        // "2026-27"
  // 26AS portal reconciliation
  portal_sr_no?: string;          // matched row from TRACES 26AS file
  portal_tds_amount?: number;
  portal_status?: "F"|"P"|"U";    // F=Final, P=Pending, U=Under Processing
  portal_booking_date?: string;
  portal_deductor_name?: string;
  match_status: "unmatched"|"matched"|"partially_matched"|"not_in_portal"|"not_in_tally";
  // JV lifecycle (same pattern as TDSDeductionEntry)
  jv_id?: string; jv_no?: string;
  status: "open"|"posted"|"cancelled";
  created_at: string;
}
export const tdsReceivableKey = (e: string) => `erp_tds_receivable_${e}`;
