/**
 * wms-putaway.ts — WMS Putaway / ASN types (Sprint WMS2 · W2 of WMS-ARC)
 *
 * @realizes WMS-ARC W2 per WMS_ARC_Step1_Alignment_v1
 *
 * Canon 5 (EximX imports): An ASN with source='eximx_import' is generated by
 * READING `importPOKey` / `billOfEntryKey` — EximX stores remain WRITE-ZERO.
 * The BoE remains customs paperwork in EximX; ASN is the physical-arrival
 * expectation in Dispatch.
 *
 * Canon 6 (Bins): BinLabel + ItemLocation are READ-ONLY foundations.
 * Suggestion ladder is honest three-step + 'none' (never fabricated).
 *
 * P8.6 floor: both record types born with `retention_policy?` + `created_by?`.
 * Both map to `operational_log_only`.
 *
 * [JWT] Wave-2: server ASN feeds (supplier EDI) + scanner-driven placement.
 */

import type { RetentionPolicyId } from '@/types/record-retention';

export type AsnSource = 'vendor_po' | 'eximx_import' | 'stock_transfer' | 'manual';

export type AsnStatus = 'expected' | 'arrived' | 'received' | 'cancelled';

export interface AsnLine {
  id: string;
  item_id: string;
  item_name: string;
  qty_expected: number;
}

export interface AsnRecord {
  id: string;
  asn_no: string;
  entity_id: string;
  fiscal_year_id?: string;
  source: AsnSource;
  /** EximX Import PO id / Stock Transfer id / Vendor PO id / null for manual */
  source_ref_id?: string;
  source_ref_no?: string;
  expected_date: string;
  godown_id?: string;
  status: AsnStatus;
  lines: AsnLine[];
  /** Set when ASN is linked to an inward-receipt downstream (never duplicate) */
  inward_receipt_id?: string;
  inward_receipt_no?: string;
  /** P8.6 floor */
  created_by?: string;
  retention_policy?: RetentionPolicyId;
  created_at: string;
  updated_at: string;
}

export type SuggestionBasis =
  | 'item_location_home'
  | 'bin_items_assigned'
  | 'capacity_headroom'
  | 'manual'
  | 'none';

export interface BinSuggestion {
  bin_label_id?: string;
  bin_location_code?: string;
  godown_id: string;
  godown_name?: string;
  basis: SuggestionBasis;
  reason: string;
}

export interface BinPlacement {
  id: string;
  entity_id: string;
  fiscal_year_id?: string;
  inward_receipt_id: string;
  inward_receipt_no: string;
  item_id: string;
  item_name: string;
  qty_placed: number;
  godown_id: string;
  bin_label_id?: string;
  bin_location_code?: string;
  placed_by?: string;
  /** AC7 · honest basis recorded on EVERY placement */
  suggestion_basis: SuggestionBasis;
  /** P8.6 floor */
  created_by?: string;
  retention_policy?: RetentionPolicyId;
  created_at: string;
  updated_at: string;
}

export const asnRecordsKey = (e: string) => `erp_wms_asn_${e}`;
export const binPlacementsKey = (e: string) => `erp_wms_bin_placements_${e}`;

export const ASN_STATUS_LABELS: Record<AsnStatus, string> = {
  expected: 'Expected',
  arrived: 'Arrived',
  received: 'Received',
  cancelled: 'Cancelled',
};

export const ASN_SOURCE_LABELS: Record<AsnSource, string> = {
  vendor_po: 'Vendor PO',
  eximx_import: 'EximX Import',
  stock_transfer: 'Stock Transfer',
  manual: 'Manual',
};

export const SUGGESTION_BASIS_LABELS: Record<SuggestionBasis, string> = {
  item_location_home: 'Item home bin',
  bin_items_assigned: 'Bin assignment',
  capacity_headroom: 'Capacity headroom',
  manual: 'Manual entry',
  none: 'No suggestion',
};
