/**
 * textile-templates.ts — 8 textile sub-sector templates (Q22=a)
 * Sprint T-Phase-1.3-3-PlantOps-pre-1 · D-571
 */
import type { ManufacturingTemplate } from './manufacturing-templates';

export const TEXTILE_TEMPLATES: ManufacturingTemplate[] = [
  {
    id: 'textile-knitting',
    category: 'industry_sector',
    name: 'Textile · Knitting',
    description: 'Circular / flat-bed knitting',
    default_costing_method: 'standard',
    default_production_model: 'mts',
    primary_kpis: ['gsm_compliance', 'machine_efficiency'],
    secondary_kpis: ['yarn_breakage'],
    enabled_modules: ['production-plan', 'job-card', 'qc-outgoing'],
    qc_parameters: [{ key: 'gsm', label: 'GSM', type: 'numeric' }],
    compliance_standards: ['OEKO-TEX'],
    icon: 'Shirt', color_class: 'bg-primary',
  },
  {
    id: 'textile-weaving',
    category: 'industry_sector',
    name: 'Textile · Weaving',
    description: 'Loom-based fabric production',
    default_costing_method: 'standard',
    default_production_model: 'mts',
    primary_kpis: ['loom_efficiency', 'pick_rate'],
    secondary_kpis: ['waste_pct'],
    enabled_modules: ['production-plan', 'oee', 'wastage'],
    qc_parameters: [{ key: 'epi', label: 'EPI', type: 'numeric' }],
    compliance_standards: [],
    icon: 'Shirt', color_class: 'bg-accent',
  },
  {
    id: 'textile-dyeing',
    category: 'industry_sector',
    name: 'Textile · Dyeing',
    description: 'Batch / continuous dyeing',
    default_costing_method: 'standard',
    default_production_model: 'mto',
    primary_kpis: ['color_fastness', 'shade_match', 'yield'],
    secondary_kpis: ['water_consumption'],
    enabled_modules: ['production-plan', 'job-card', 'qc-outgoing', 'wastage'],
    qc_parameters: [
      { key: 'color_fastness', label: 'Color Fastness', type: 'numeric' },
      { key: 'shade_match', label: 'Shade Match', type: 'pass_fail' },
    ],
    compliance_standards: ['ZDHC'],
    icon: 'Droplet', color_class: 'bg-warning',
  },
  {
    id: 'textile-printing',
    category: 'industry_sector',
    name: 'Textile · Printing',
    description: 'Rotary / digital fabric printing',
    default_costing_method: 'standard',
    default_production_model: 'mto',
    primary_kpis: ['print_yield', 'registration_accuracy'],
    secondary_kpis: ['rework_pct'],
    enabled_modules: ['production-plan', 'job-card', 'qc-outgoing'],
    qc_parameters: [{ key: 'registration_mm', label: 'Registration (mm)', type: 'numeric' }],
    compliance_standards: [],
    icon: 'Printer', color_class: 'bg-primary',
  },
  {
    id: 'textile-finishing',
    category: 'industry_sector',
    name: 'Textile · Finishing',
    description: 'Stentering / calendaring / sanforizing',
    default_costing_method: 'standard',
    default_production_model: 'mto',
    primary_kpis: ['shrinkage_pct', 'hand_feel'],
    secondary_kpis: ['oee'],
    enabled_modules: ['production-plan', 'qc-outgoing'],
    qc_parameters: [{ key: 'shrinkage_pct', label: 'Shrinkage (%)', type: 'numeric' }],
    compliance_standards: [],
    icon: 'Sparkles', color_class: 'bg-accent',
  },
  {
    id: 'textile-garment',
    category: 'industry_sector',
    name: 'Textile · Garment',
    description: 'Cut-make-trim garment assembly',
    default_costing_method: 'actual',
    default_production_model: 'mto',
    primary_kpis: ['smv_efficiency', 'first_pass_yield', 'on_time_delivery'],
    secondary_kpis: ['rework_pct'],
    enabled_modules: ['production-plan', 'job-card', 'qc-outgoing'],
    qc_parameters: [
      { key: 'measurement_check', label: 'Measurement Check', type: 'pass_fail' },
      { key: 'visual_aql', label: 'Visual AQL', type: 'pass_fail' },
    ],
    compliance_standards: ['SA8000', 'WRAP'],
    icon: 'Scissors', color_class: 'bg-warning',
  },
  {
    id: 'textile-technical',
    category: 'industry_sector',
    name: 'Textile · Technical',
    description: 'Industrial / functional textiles',
    default_costing_method: 'standard',
    default_production_model: 'mto',
    primary_kpis: ['tensile_strength', 'specification_compliance'],
    secondary_kpis: [],
    enabled_modules: ['production-plan', 'job-card', 'qc-outgoing'],
    qc_parameters: [{ key: 'tensile_n', label: 'Tensile (N)', type: 'numeric' }],
    compliance_standards: ['ISO9001'],
    icon: 'Layers', color_class: 'bg-primary',
  },
  {
    id: 'textile-yarn-spinning',
    category: 'industry_sector',
    name: 'Textile · Yarn Spinning',
    description: 'Ring / open-end yarn spinning',
    default_costing_method: 'standard',
    default_production_model: 'mts',
    primary_kpis: ['count_variation', 'yarn_strength', 'spindle_efficiency'],
    secondary_kpis: ['hairiness'],
    enabled_modules: ['production-plan', 'oee', 'qc-outgoing'],
    qc_parameters: [
      { key: 'yarn_count', label: 'Yarn Count', type: 'numeric' },
      { key: 'tensile_cn', label: 'Tensile (cN/tex)', type: 'numeric' },
    ],
    compliance_standards: [],
    icon: 'Spool', color_class: 'bg-accent',
  },
];

export function getTextileTemplateById(id: string): ManufacturingTemplate | undefined {
  return TEXTILE_TEMPLATES.find(t => t.id === id);
}
