import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Smartphone, ArrowLeft, CheckCircle2, FileText, CalendarDays, Clock, IndianRupee } from 'lucide-react';

const FEATURES = [
  {
    icon: IndianRupee,
    title: 'Payslip & Pay',
    desc: 'View and download payslips for every month. See CTC breakup, all earnings and deductions, PF and TDS details. Form 16 download when generated by HR. Loan EMI schedule and outstanding balance. All salary history in one place.',
  },
  {
    icon: CalendarDays,
    title: 'Leave Management',
    desc: 'Apply for leave from the phone — select type, dates, reason, and submit. Real-time leave balance (EL, CL, SL). Track application status from submitted to approved. Cancel pending applications. View team leave calendar to avoid overlaps.',
  },
  {
    icon: Clock,
    title: 'Attendance',
    desc: 'View monthly attendance summary — present, absent, half-days, overtime, late marks. Check-in and check-out timestamps if biometric or geo-fence is enabled. Apply for regularisation for missed punches. Day-wise detail with shift and remark.',
  },
  {
    icon: FileText,
    title: 'Documents & IT',
    desc: 'Download HR documents — offer letter, appointment, salary revision, experience letter, Form 16. Submit IT declaration (80C, 80D, HRA, housing loan) and Form 12BB proof uploads. View TDS workings and projected tax for the year.',
  },
];

const COMPARE = [
  { feature: 'Payslip access',         web: 'Full payslip in ERP portal',           app: 'PDF view + download on phone' },
  { feature: 'Leave application',      web: 'Full leave module with all rules',     app: 'Apply, track, cancel — simplified' },
  { feature: 'Leave balance',          web: 'Full balance sheet with accrual',      app: 'Current balance per type' },
  { feature: 'Attendance summary',     web: 'Daily grid with full detail',          app: 'Monthly summary + day detail' },
  { feature: 'Regularisation',         web: 'Full regularisation workflow',         app: 'Apply from phone' },
  { feature: 'IT declaration',         web: 'Full Form 12BB with file upload',      app: 'Declare + upload proof' },
  { feature: 'Form 16 download',       web: 'Part A + B full document',             app: 'PDF download' },
  { feature: 'Loan statement',         web: 'Full schedule with balance',           app: 'Summary + outstanding' },
  { feature: 'Expense claim submit',   web: 'Full claim form with approvals',       app: 'Submit + track status' },
  { feature: 'Announcements',          web: 'Full inbox with priority and expiry',  app: 'Inbox view only' },
  { feature: 'Document downloads',     web: 'All HR documents with version',        app: 'Download available documents' },
  { feature: 'Profile edit',           web: 'Full employee profile',                app: 'Contact + bank details (if enabled)' },
  { feature: 'Requires ERP login?',    web: 'Yes — full ERP credentials',           app: 'No — separate ESS login' },
];

const SAAS_TIERS = [
  {
    name: 'Included',
    price: 'No extra charge',
    scope: 'Vetan Nidhi HR+Payroll tier · Operix ERP Professional+',
    color: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300',
    conditions: [
      'Included in Vetan Nidhi HR+Payroll, Professional, and Enterprise tiers',
      'Included in Operix ERP PeoplePay — Professional and above',
      'All ESS features enabled by default — HR toggles each feature in ESS Config',
      'White-label portal available on Vetan Nidhi Professional+',
      'No per-employee mobile licence fee',
    ],
  },
  {
    name: 'Standalone Add-on',
    price: '₹49 – ₹99 / employee / month',
    scope: 'For Vetan Nidhi Starter or Payroll Starter subscribers',
    color: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',
    conditions: [
      'Add the Employee app to any Vetan Nidhi tier',
      'Payslip access + leave + attendance view',
      'IT declaration and Form 16 download',
      'HR controls feature access via ESS Config',
      'Billed per active employee per month',
    ],
  },
  {
    name: 'Enterprise White-Label',
    price: 'Custom pricing',
    scope: 'Enterprise / Bureau tier only',
    color: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
    conditions: [
      'Your company name and logo throughout the app',
      'Custom domain — employees access via yourcompany.sahayak.app',
      'Custom colour theme matching brand guidelines',
      'Push notifications for payslip release and leave approval',
      'SSO integration (Google Workspace, Microsoft 365)',
    ],
  },
];

const STEPS = [
  {
    step: 1,
    title: 'Standalone Auth Shell',
    desc: 'Separate login route /operix-go/login with employee credentials (empCode + password). No ERP session required. JWT issued by the same auth service but with ESS-only scope. Auto-detect entity from employee record.',
  },
  {
    step: 2,
    title: 'Feature Gate from ESS Config',
    desc: 'On login, fetch ESSConfig for the tenant. Show or hide payslip, leave, attendance, IT declaration, expense, document tabs based on what HR has enabled. The same ESSConfig already built in AdminAndMonitoring drives the mobile app completely.',
  },
  {
    step: 3,
    title: 'Payslip & Documents',
    desc: 'Reuse payslip data from usePayrollEngine — render as mobile-optimised card (not the desktop payslip layout). PDF download via existing PayslipGeneration export logic. Form 16 reads from the same erp_payroll_runs storage.',
  },
  {
    step: 4,
    title: 'Leave & Attendance',
    desc: 'Reuse useLeaveManagement hook and LeaveRequests logic. Render as card-based mobile UI — leave type chips, date pickers, submit button. Attendance reads erp_attendance_records filtered by employeeId. Regularisation form reuses existing AttendanceEntry logic.',
  },
  {
    step: 5,
    title: 'PWA Manifest + Push',
    desc: 'Add manifest.json (name: Sahayak, theme_color: violet, display: standalone, icons). Register service worker for offline payslip caching. Push notifications via Web Push API — trigger on payslip publish and leave status change. Works on Android and iOS Safari without app store.',
  },
];

export default function EmployeeApp() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-5xl mx-auto p-6 space-y-8">
        <Button variant="ghost" size="sm" onClick={() => navigate('/operix-go')}>
          <ArrowLeft className="h-4 w-4 mr-1" />Back to Operix Go
        </Button>
        {/* Header */}
        <div className="flex items-start gap-4">
          <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
            <Smartphone className="h-6 w-6 text-primary" />
          </div>
          <div>
            <div className="flex items-center gap-3 flex-wrap">
              <h1 className="text-2xl font-bold">Sahayak — Employee</h1>
              <span className="text-lg text-muted-foreground font-normal">— सहायक कर्मचारी</span>
              <Badge className="bg-amber-100 text-amber-700 dark:bg-amber-900 dark:text-amber-300">Phase 2</Badge>
            </div>
            <p className="text-sm text-muted-foreground mt-1">
              Mobile ESS for every employee — payslips, leave, attendance, IT declaration.
              No app install. Works in any phone browser.
            </p>
          </div>
        </div>
        {/* What it does */}
        <div className="rounded-lg border-2 border-dashed p-6">
          <h2 className="text-lg font-semibold mb-2">What Sahayak Employee does</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Every employee in your organisation can access their complete HR information from
            their phone — without calling HR, without waiting for the desktop. Apply for leave
            at midnight from home. Download the payslip the minute it is published. Submit IT
            declaration proofs in January without coming to the office. Check attendance and
            apply for regularisation on the same day. Sahayak Employee is a Progressive Web App
            (PWA) — no app store, no installation. HR controls exactly what employees can see
            and do using the ESS Config toggles already built in Operix Pay Hub.
          </p>
        </div>
        {/* Features */}
        <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">
          {FEATURES.map(f => (
            <Card key={f.title}>
              <CardHeader className="pb-2">
                <CardTitle className="text-base flex items-center gap-2">
                  <f.icon className="h-5 w-5 text-primary" />{f.title}
                </CardTitle>
              </CardHeader>
              <CardContent><p className="text-xs text-muted-foreground leading-relaxed">{f.desc}</p></CardContent>
            </Card>
          ))}
        </div>
        {/* Comparison */}
        <div>
          <h2 className="text-lg font-semibold mb-3">Web ERP vs Employee App</h2>
          <div className="rounded-md border overflow-x-auto">
            <Table>
              <TableHeader><TableRow>
                <TableHead className="w-48">Feature</TableHead>
                <TableHead>Web ERP (PeoplePay)</TableHead>
                <TableHead>Sahayak Employee App</TableHead>
              </TableRow></TableHeader>
              <TableBody>
                {COMPARE.map(r => (
                  <TableRow key={r.feature}>
                    <TableCell className="font-medium text-sm">{r.feature}</TableCell>
                    <TableCell className="text-sm">{r.web}</TableCell>
                    <TableCell className="text-sm">{r.app}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </div>
        {/* SaaS Tiers */}
        <div>
          <h2 className="text-lg font-semibold mb-1">Pricing</h2>
          <p className="text-sm text-muted-foreground mb-4">
            Included in higher tiers. Available as a per-employee add-on for lower tiers.
            Enterprise white-label for custom branding.
          </p>
          <div className="grid sm:grid-cols-3 gap-4">
            {SAAS_TIERS.map(tier => (
              <div key={tier.name} className="rounded-xl border bg-card/60 p-5 space-y-3">
                <Badge className={tier.color}>{tier.name}</Badge>
                <div>
                  <p className="text-base font-bold">{tier.price}</p>
                  <p className="text-xs text-muted-foreground">{tier.scope}</p>
                </div>
                <ul className="space-y-1.5">
                  {tier.conditions.map(c => (
                    <li key={c} className="flex items-start gap-2 text-xs text-muted-foreground">
                      <CheckCircle2 className="h-3 w-3 text-green-500 mt-0.5 shrink-0" />{c}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
        {/* Build guide */}
        <div>
          <h2 className="text-lg font-semibold mb-3">Developer Build Guide</h2>
          <div className="space-y-3">
            {STEPS.map(s => (
              <div key={s.step} className="flex gap-4 items-start">
                <div className="h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center shrink-0 text-sm font-bold text-primary">{s.step}</div>
                <div>
                  <p className="text-sm font-medium">{s.title}</p>
                  <p className="text-xs text-muted-foreground">{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
        {/* Phase rationale */}
        <div className="flex items-start gap-3 rounded-lg border border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-950/30 p-4">
          <CheckCircle2 className="h-5 w-5 text-green-600 dark:text-green-400 mt-0.5 shrink-0" />
          <div>
            <p className="text-sm font-medium text-green-800 dark:text-green-300">Why Phase 2?</p>
            <p className="text-xs text-green-600 dark:text-green-400 mt-1">
              The ESSConfig, ESS toggle system, leave approval workflow, payslip generation,
              and attendance module in PeoplePay must be production-stable before the mobile
              shell is built. The app is a thin mobile wrapper over already-built ERP logic.
              Phase 1 (ERP PeoplePay + ESS Config) is complete. Phase 2 (Sahayak PWA) begins
              after ERP stabilisation and the Vetan Nidhi standalone launch.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
