/**
 * command-center-sidebar-config.ts — Data config replacing CommandCenterSidebar.tsx
 *
 * Structure matches the full Command Centre module set defined in CommandCenterPage.
 * Module IDs are PRESERVED — CommandCenterPage's activeModule state depends on them.
 */

import {
  LayoutDashboard, Building2, Globe, Landmark, Lock,
  Settings2, Grid3X3, Hash, Boxes, Tags, Tag, Warehouse, Ruler,
  Package, LayoutTemplate, QrCode, ScanLine, MapPin, Printer, Wifi,
  PackageOpen, DollarSign, TrendingDown, AlertTriangle,
  Upload, BookOpen, HandCoins, Users, ShoppingCart, CreditCard,
  Truck, Network, Layers, Briefcase, FileText, ListChecks,
  Receipt,
} from 'lucide-react';
import type { SidebarItem } from '@/shell/types';

export const commandCenterSidebarItems: SidebarItem[] = [
  {
    id: 'overview', type: 'item', label: 'Overview', icon: LayoutDashboard,
    moduleId: 'overview', requiredCards: ['command-center'], keyboard: 'g o',
  },
  {
    id: 'foundation-group', type: 'group', label: 'Foundation & Core', icon: Building2,
    children: [
      { id: 'foundation', type: 'item', label: 'Entity Management', icon: Building2,
        moduleId: 'foundation', requiredCards: ['command-center'] },
      { id: 'geography', type: 'item', label: 'Geography', icon: Globe,
        moduleId: 'geography', requiredCards: ['command-center'] },
      { id: 'org-structure', type: 'item', label: 'Business Units', icon: Network,
        moduleId: 'org-structure', requiredCards: ['command-center'] },
      { id: 'finecore-business-unit', type: 'item', label: 'Business Units Master', icon: Layers,
        moduleId: 'finecore-business-unit', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'finance-hub-group', type: 'group', label: 'Finance & Compliance', icon: Landmark,
    children: [
      { id: 'finecore-hub', type: 'item', label: 'Hub Overview',
        moduleId: 'finecore-hub', requiredCards: ['command-center'] },
      { id: 'finecore-tax-rates', type: 'item', label: 'GST Rate Reference',
        moduleId: 'finecore-tax-rates', requiredCards: ['command-center'] },
      { id: 'finecore-tds', type: 'item', label: 'TDS Sections',
        moduleId: 'finecore-tds', requiredCards: ['command-center'] },
      { id: 'finecore-tcs', type: 'item', label: 'TCS Sections',
        moduleId: 'finecore-tcs', requiredCards: ['command-center'] },
      { id: 'finecore-hsn-sac', type: 'item', label: 'HSN / SAC Directory',
        moduleId: 'finecore-hsn-sac', requiredCards: ['command-center'] },
      { id: 'finecore-epf-esi-lwf', type: 'item', label: 'Payroll Statutory',
        moduleId: 'finecore-epf-esi-lwf', requiredCards: ['command-center'] },
      { id: 'finecore-income-tax', type: 'item', label: 'Income Tax Reference',
        moduleId: 'finecore-income-tax', requiredCards: ['command-center'] },
      { id: 'finecore-professional-tax', type: 'item', label: 'Professional Tax',
        moduleId: 'finecore-professional-tax', requiredCards: ['command-center'] },
      { id: 'fc-divider-1', type: 'divider', label: '' },
      { id: 'finecore-statutory-reg', type: 'item', label: 'Statutory Registrations',
        moduleId: 'finecore-statutory-reg', requiredCards: ['command-center'] },
      { id: 'finecore-gst-config', type: 'item', label: 'GST Entity Config',
        moduleId: 'finecore-gst-config', requiredCards: ['command-center'] },
      { id: 'finecore-compliance-settings', type: 'item', label: 'Compliance Settings & Automation',
        moduleId: 'finecore-compliance-settings', requiredCards: ['command-center'] },
      { id: 'fc-divider-2', type: 'divider', label: '' },
      { id: 'finecore-currency', type: 'item', label: 'Currency Master',
        moduleId: 'finecore-currency', requiredCards: ['command-center'] },
      { id: 'finecore-finframe', type: 'item', label: 'FinFrame — Account Groups',
        moduleId: 'finecore-finframe', requiredCards: ['command-center'] },
      { id: 'finecore-ledgers', type: 'item', label: 'Ledger Master',
        moduleId: 'finecore-ledgers', requiredCards: ['command-center'] },
      { id: 'finecore-voucher-types', type: 'item', label: 'Voucher Types',
        moduleId: 'finecore-voucher-types', requiredCards: ['command-center'] },
      { id: 'finecore-transaction-templates', type: 'item', label: 'Transaction Templates',
        moduleId: 'finecore-transaction-templates', requiredCards: ['command-center'] },
      { id: 'fc-divider-3', type: 'divider', label: '' },
      { id: 'finecore-mode-of-payment', type: 'item', label: 'Mode of Payment',
        moduleId: 'finecore-mode-of-payment', requiredCards: ['command-center'] },
      { id: 'finecore-terms-of-payment', type: 'item', label: 'Terms of Payment',
        moduleId: 'finecore-terms-of-payment', requiredCards: ['command-center'] },
      { id: 'finecore-terms-of-delivery', type: 'item', label: 'Terms of Delivery',
        moduleId: 'finecore-terms-of-delivery', requiredCards: ['command-center'] },
      { id: 'finecore-fiscal-year', type: 'item', label: 'Fiscal Year Calendar',
        moduleId: 'finecore-fiscal-year', requiredCards: ['command-center'] },
      { id: 'finecore-asset-centres', type: 'item', label: 'Asset Centres', icon: Building2,
        moduleId: 'finecore-asset-centres', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'projx-masters-group', type: 'group', label: 'Project Masters', icon: Briefcase,
    children: [
      { id: 'projx-project-centres', type: 'item', label: 'Project Centres', icon: Briefcase,
        moduleId: 'projx-project-centres', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'inventory-group', type: 'group', label: 'Inventory Masters', icon: Package,
    children: [
      { id: 'inventory-parametric', type: 'item', label: 'Parametric Hub', icon: Settings2,
        moduleId: 'inventory-parametric', requiredCards: ['command-center'] },
      { id: 'inventory-batch', type: 'item', label: 'Batch Grid', icon: Grid3X3,
        moduleId: 'inventory-batch', requiredCards: ['command-center'] },
      { id: 'inventory-serial', type: 'item', label: 'Serial Grid', icon: Hash,
        moduleId: 'inventory-serial', requiredCards: ['command-center'] },
      { id: 'inventory-stock-matrix', type: 'item', label: 'Stock Matrix', icon: Boxes,
        moduleId: 'inventory-stock-matrix', requiredCards: ['command-center'] },
      { id: 'inventory-classify', type: 'item', label: 'Classifications', icon: Tags,
        moduleId: 'inventory-classify', requiredCards: ['command-center'] },
      { id: 'inventory-brands', type: 'item', label: 'Brand Matrix', icon: Tag,
        moduleId: 'inventory-brands', requiredCards: ['command-center'] },
      { id: 'inventory-storage', type: 'item', label: 'Storage Matrix', icon: Warehouse,
        moduleId: 'inventory-storage', requiredCards: ['command-center'] },
      { id: 'inventory-uom', type: 'item', label: 'Measure X', icon: Ruler,
        moduleId: 'inventory-uom', requiredCards: ['command-center'] },
      { id: 'inventory-item-craft', type: 'item', label: 'Item Craft', icon: Package,
        moduleId: 'inventory-item-craft', requiredCards: ['command-center'] },
      { id: 'inventory-code-matrix', type: 'item', label: 'Code Matrix', icon: Hash,
        moduleId: 'inventory-code-matrix', requiredCards: ['command-center'] },
      { id: 'inventory-item-templates', type: 'item', label: 'Item Templates', icon: LayoutTemplate,
        moduleId: 'inventory-item-templates', requiredCards: ['command-center'] },
      { id: 'inventory-opening-stock', type: 'item', label: 'Opening Stock Entry', icon: PackageOpen,
        moduleId: 'inventory-opening-stock', requiredCards: ['command-center'] },
      { id: 'inventory-item-rates', type: 'item', label: 'Rates & MRP', icon: DollarSign,
        moduleId: 'inventory-item-rates', requiredCards: ['command-center'] },
      { id: 'inventory-price-lists', type: 'item', label: 'Price Lists', icon: TrendingDown,
        moduleId: 'inventory-price-lists', requiredCards: ['command-center'] },
      { id: 'inventory-reorder', type: 'item', label: 'Reorder & Min-Max', icon: AlertTriangle,
        moduleId: 'inventory-reorder', requiredCards: ['command-center'] },
      { id: 'inventory-label-templates', type: 'item', label: 'Label Templates', icon: Tag,
        moduleId: 'inventory-label-templates', requiredCards: ['command-center'] },
      { id: 'inventory-barcode-gen', type: 'item', label: 'Barcode Generator', icon: QrCode,
        moduleId: 'inventory-barcode-gen', requiredCards: ['command-center'] },
      { id: 'inventory-asset-tags', type: 'item', label: 'Asset Tag Manager', icon: ScanLine,
        moduleId: 'inventory-asset-tags', requiredCards: ['command-center'] },
      { id: 'inventory-bin-labels', type: 'item', label: 'Bin Location Labels', icon: MapPin,
        moduleId: 'inventory-bin-labels', requiredCards: ['command-center'] },
      { id: 'inventory-print-queue', type: 'item', label: 'Print Queue', icon: Printer,
        moduleId: 'inventory-print-queue', requiredCards: ['command-center'] },
      { id: 'inventory-rfid', type: 'item', label: 'RFID Manager', icon: Wifi,
        moduleId: 'inventory-rfid', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'procurement-sourcing-group', type: 'group', label: 'Procurement & Sourcing', icon: ShoppingCart,
    children: [
      { id: 'requestx-voucher-types', type: 'item', label: 'RequestX Voucher Types', icon: FileText,
        moduleId: 'requestx-voucher-types', requiredCards: ['command-center'] },
      { id: 'approval-matrix-templates', type: 'item', label: 'Approval Matrix Templates', icon: ListChecks,
        moduleId: 'approval-matrix-templates', requiredCards: ['command-center'] },
      { id: 'pinned-templates-master', type: 'item', label: 'Pinned Templates', icon: Tag,
        moduleId: 'pinned-templates-master', requiredCards: ['command-center'] },
      // T-Phase-1.2.6f-b-2-fix-1 · Block N · D-277 · CCV-1 reorg · Vendor MOVED here from CRM · Logistic ADDED
      { id: 'crm-vendor', type: 'item', label: 'Vendor Master', icon: Users,
        moduleId: 'crm-vendor', requiredCards: ['command-center'] },
      { id: 'crm-logistic', type: 'item', label: 'Logistic Master', icon: Truck,
        moduleId: 'crm-logistic', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'people-core-group', type: 'group', label: 'People Core', icon: Users,
    children: [
      { id: 'ph-employee', type: 'item', label: 'Employee Master',
        moduleId: 'ph-employee', requiredCards: ['command-center'] },
      { id: 'ph-pay-heads', type: 'item', label: 'Pay Heads',
        moduleId: 'ph-pay-heads', requiredCards: ['command-center'] },
      { id: 'ph-salary-structures', type: 'item', label: 'Salary Structures',
        moduleId: 'ph-salary-structures', requiredCards: ['command-center'] },
      { id: 'ph-pay-grades', type: 'item', label: 'Pay Grades',
        moduleId: 'ph-pay-grades', requiredCards: ['command-center'] },
      { id: 'ph-shifts', type: 'item', label: 'Shifts',
        moduleId: 'ph-shifts', requiredCards: ['command-center'] },
      { id: 'ph-leave-types', type: 'item', label: 'Leave Types',
        moduleId: 'ph-leave-types', requiredCards: ['command-center'] },
      { id: 'ph-holiday-calendar', type: 'item', label: 'Holiday Calendar',
        moduleId: 'ph-holiday-calendar', requiredCards: ['command-center'] },
      { id: 'ph-attendance-types', type: 'item', label: 'Attendance Types',
        moduleId: 'ph-attendance-types', requiredCards: ['command-center'] },
      { id: 'ph-overtime-rules', type: 'item', label: 'Overtime Rules',
        moduleId: 'ph-overtime-rules', requiredCards: ['command-center'] },
      { id: 'ph-loan-types', type: 'item', label: 'Loan Types',
        moduleId: 'ph-loan-types', requiredCards: ['command-center'] },
      { id: 'ph-bonus-config', type: 'item', label: 'Bonus Config',
        moduleId: 'ph-bonus-config', requiredCards: ['command-center'] },
      { id: 'ph-gratuity-nps', type: 'item', label: 'Gratuity & NPS',
        moduleId: 'ph-gratuity-nps', requiredCards: ['command-center'] },
      { id: 'ph-asset-master', type: 'item', label: 'Asset Master',
        moduleId: 'ph-asset-master', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'crm-group', type: 'group', label: 'CRM Masters', icon: Users,
    children: [
      { id: 'crm-hub', type: 'item', label: 'Hub Overview',
        moduleId: 'crm-hub', requiredCards: ['command-center'] },
      { id: 'crm-customer', type: 'item', label: 'Customer Master',
        moduleId: 'crm-customer', requiredCards: ['command-center'] },
      { id: 'crm-customer-segments', type: 'item', label: 'Customer Segments',
        moduleId: 'crm-customer-segments', requiredCards: ['command-center'] },
      // crm-vendor moved to procurement-sourcing-group per D-277 (CCV-1 reorganization)
    ],
  },
  {
    id: 'sales-group', type: 'group', label: 'Sales Masters', icon: ShoppingCart,
    children: [
      { id: 'sales-hub', type: 'item', label: 'Hub Overview',
        moduleId: 'sales-hub', requiredCards: ['command-center'] },
      { id: 'sales-hierarchy', type: 'item', label: 'Hierarchy',
        moduleId: 'sales-hierarchy', requiredCards: ['command-center'] },
      { id: 'sales-sam-person', type: 'item', label: 'Salesman / SAM',
        moduleId: 'sales-sam-person', requiredCards: ['command-center'] },
      { id: 'sales-enquiry-source', type: 'item', label: 'Enquiry Sources',
        moduleId: 'sales-enquiry-source', requiredCards: ['command-center'] },
      { id: 'sales-campaign', type: 'item', label: 'Campaigns',
        moduleId: 'sales-campaign', requiredCards: ['command-center'] },
      { id: 'sales-territory', type: 'item', label: 'Territories',
        moduleId: 'sales-territory', requiredCards: ['command-center'] },
      { id: 'sales-beat-route', type: 'item', label: 'Beat Routes',
        moduleId: 'sales-beat-route', requiredCards: ['command-center'] },
      { id: 'sales-target', type: 'item', label: 'Targets',
        moduleId: 'sales-target', requiredCards: ['command-center'] },
      { id: 'sales-schemes', type: 'item', label: 'Schemes',
        moduleId: 'sales-schemes', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'collection-group', type: 'group', label: 'Collection Masters', icon: CreditCard,
    children: [
      { id: 'collection-hub', type: 'item', label: 'Hub Overview',
        moduleId: 'collection-hub', requiredCards: ['command-center'] },
      { id: 'collection-exec', type: 'item', label: 'Collection Executives',
        moduleId: 'collection-exec', requiredCards: ['command-center'] },
      { id: 'collection-incentive', type: 'item', label: 'Incentive Schemes',
        moduleId: 'collection-incentive', requiredCards: ['command-center'] },
      { id: 'collection-reminder', type: 'item', label: 'Reminder Templates',
        moduleId: 'collection-reminder', requiredCards: ['command-center'] },
      { id: 'collection-config', type: 'item', label: 'ReceivX Config',
        moduleId: 'collection-config', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'distributor-group', type: 'group', label: 'Distributor Masters', icon: Truck,
    children: [
      { id: 'distributor-hub', type: 'item', label: 'Hub Overview',
        moduleId: 'distributor-hub', requiredCards: ['command-center'] },
      { id: 'distributor-hierarchy', type: 'item', label: 'Hierarchy',
        moduleId: 'distributor-hierarchy', requiredCards: ['command-center'] },
      { id: 'distributor-price-list', type: 'item', label: 'Price Lists',
        moduleId: 'distributor-price-list', requiredCards: ['command-center'] },
      { id: 'distributor-credit-refs', type: 'item', label: 'Credit Reference',
        moduleId: 'distributor-credit-refs', requiredCards: ['command-center'] },
      { id: 'distributor-dispute-refs', type: 'item', label: 'Dispute Reference',
        moduleId: 'distributor-dispute-refs', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'opening-group', type: 'group', label: 'Opening Balances', icon: BookOpen,
    children: [
      { id: 'opening-inventory', type: 'item', label: 'Opening Stock Entry', icon: PackageOpen,
        moduleId: 'inventory-opening-stock', requiredCards: ['command-center'] },
      { id: 'opening-ledger-balances', type: 'item', label: 'Ledger Opening Balances', icon: BookOpen,
        moduleId: 'opening-ledger-balances', requiredCards: ['command-center'] },
      { id: 'opening-employee-loans', type: 'item', label: 'Employee Opening Loans', icon: HandCoins,
        moduleId: 'opening-employee-loans', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'console-group', type: 'group', label: 'Security Console', icon: Lock,
    children: [
      { id: 'console', type: 'item', label: 'Security Console', icon: Lock,
        moduleId: 'console', requiredCards: ['command-center'] },
    ],
  },
  {
    id: 'utility-group', type: 'group', label: 'Utilities', icon: Upload,
    children: [
      { id: 'utility-import', type: 'item', label: 'Import Hub', icon: Upload,
        moduleId: 'utility-import', requiredCards: ['command-center'] },
    ],
  },
];
