/**
 * @file        qualicheck-sidebar-config.ts
 * @purpose     Sidebar data config for QualiCheck (QualiCheck) · 30+ modules in 5 sections +
 *              Trident QC Reports sub-group (Q-LOCK-6b)
 * @who         Quality Inspector · QA Manager · Vendor Manager
 * @when        Phase 1.A.5.a · QualiCheck Shell Migration sprint
 * @sprint      T-Phase-1.A.5.a-QualiCheck-Shell-Migration · T-Phase-1.A.5.c-T3-AuditFix ·
 *              F-8 keyboard duplicate resolved (welder-qualification 'q w' → 'q l') ·
 *              T-Phase-1.A.5.d-2-AuditFix
 * @iso         Maintainability · Usability
 * @decisions   D-250 (Shell pattern · FR-58) · D-NEW-AY (Outcome C · split α-a into
 *              Shell migration + α-a-bis NCR Foundation) ·
 *              D-NEW-AZ (QualiCheckSidebar.tsx DELETED · sidebar data extracted to config) ·
 *              Q-LOCK-6b (Trident QC Reports sub-group · α-d-2)
 * @reuses      @/shell/types SidebarItem · lucide-react icons
 * @[JWT]       N/A (config only)
 *
 * Module IDs PRESERVED from existing QualiCheckSidebar.types.ts QualiCheckModule type
 * to avoid breaking QualiCheckPage's renderModule() switch.
 */
import {
  Home, ClipboardCheck, FileText, Beaker, ListChecks,
  ShieldCheck, Award, FileCheck, AlertTriangle, Layers, Factory, BarChart3,
  AlertOctagon, FileWarning, Wrench, FileBadge, Ruler, Clock,
  HardHat, Users,
} from 'lucide-react';
import type { SidebarItem } from '@/shell/types';

export const qualicheckSidebarItems: SidebarItem[] = [
  {
    id: 'welcome',
    type: 'item',
    label: 'Welcome',
    icon: Home,
    moduleId: 'welcome',
    requiredCards: ['qualicheck'],
    keyboard: 'q w',
  },
  {
    id: 'operations-group',
    type: 'group',
    label: 'Operations',
    icon: ClipboardCheck,
    children: [
      {
        id: 'pending-inspections',
        type: 'item',
        label: 'Pending Inspections',
        icon: ClipboardCheck,
        moduleId: 'pending-inspections',
        requiredCards: ['qualicheck'],
        keyboard: 'q p',
      },
      {
        id: 'production-qc-pending',
        type: 'item',
        label: 'Production QC',
        icon: Factory,
        moduleId: 'production-qc-pending',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'pending-alerts',
        type: 'item',
        label: 'Pending Alerts',
        icon: AlertTriangle,
        moduleId: 'pending-alerts',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'closure-log',
        type: 'item',
        label: 'Closure Log',
        icon: ShieldCheck,
        moduleId: 'closure-log',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'ncr-capture',
        type: 'item',
        label: 'Raise NCR',
        icon: AlertOctagon,
        moduleId: 'ncr-capture',
        requiredCards: ['qualicheck'],
        keyboard: 'q n',
      },
      {
        id: 'capa-capture',
        type: 'item',
        label: 'Raise CAPA',
        icon: Wrench,
        moduleId: 'capa-capture',
        requiredCards: ['qualicheck'],
        keyboard: 'q c',
      },
      {
        id: 'mtc-capture',
        type: 'item',
        label: 'Capture MTC',
        icon: FileBadge,
        moduleId: 'mtc-capture',
        requiredCards: ['qualicheck'],
        keyboard: 'q m',
      },
      {
        id: 'fai-capture',
        type: 'item',
        label: 'Capture FAI',
        icon: Ruler,
        moduleId: 'fai-capture',
        requiredCards: ['qualicheck'],
        keyboard: 'q f',
      },
      {
        id: 'welder-qualification',
        type: 'item',
        label: 'Welder Qualification',
        icon: HardHat,
        moduleId: 'welder-qualification',
        requiredCards: ['qualicheck'],
        keyboard: 'q l',
      },
      {
        id: 'iqc-entry-page',
        type: 'item',
        label: 'IQC Entry',
        icon: ClipboardCheck,
        moduleId: 'iqc-entry-page',
        requiredCards: ['qualicheck'],
        keyboard: 'q i',
      },
      {
        id: 'iso9001-capture',
        type: 'item',
        label: 'ISO 9001 Audit',
        icon: FileCheck,
        moduleId: 'iso9001-capture',
        requiredCards: ['qualicheck'],
        keyboard: 'q s',
      },
    ],
  },
  {
    id: 'masters-group',
    type: 'group',
    label: 'Masters',
    icon: FileText,
    children: [
      {
        id: 'quality-plans',
        type: 'item',
        label: 'Quality Plans',
        icon: FileText,
        moduleId: 'quality-plans',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'quality-specs',
        type: 'item',
        label: 'Quality Specs',
        icon: Beaker,
        moduleId: 'quality-specs',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'bulk-plan-assignment',
        type: 'item',
        label: 'Bulk Plan Assignment',
        icon: Layers,
        moduleId: 'bulk-plan-assignment',
        requiredCards: ['qualicheck'],
      },
    ],
  },
  {
    id: 'reports-group',
    type: 'group',
    label: 'Reports',
    icon: BarChart3,
    children: [
      {
        id: 'qc-dashboard',
        type: 'item',
        label: 'QC Dashboard',
        icon: BarChart3,
        moduleId: 'qc-dashboard',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'inspection-register',
        type: 'item',
        label: 'Inspection Register',
        icon: ListChecks,
        moduleId: 'inspection-register',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'vendor-scorecard',
        type: 'item',
        label: 'Vendor Scorecard',
        icon: Award,
        moduleId: 'vendor-scorecard',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'coa-register',
        type: 'item',
        label: 'CoA Register',
        icon: FileCheck,
        moduleId: 'coa-register',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'ncr-register',
        type: 'item',
        label: 'NCR Register',
        icon: FileWarning,
        moduleId: 'ncr-register',
        requiredCards: ['qualicheck'],
      },
      // ─── NEW · SM.QualiCheck-NCR-Evidence · D-NEW-CJ 4th CONSUMER · INSTITUTIONAL FR PROMOTION THRESHOLD MET ───
      {
        id: 'ncr-evidence-register',
        type: 'item',
        label: 'NCR Evidence',
        icon: FileText,
        moduleId: 'ncr-evidence-register',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'ncr-evidence-entry',
        type: 'item',
        label: 'New NCR Evidence',
        icon: FileText,
        moduleId: 'ncr-evidence-entry',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'capa-register',
        type: 'item',
        label: 'CAPA Register',
        icon: Wrench,
        moduleId: 'capa-register',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'mtc-register',
        type: 'item',
        label: 'MTC Register',
        icon: FileBadge,
        moduleId: 'mtc-register',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'fai-register',
        type: 'item',
        label: 'FAI Register',
        icon: Ruler,
        moduleId: 'fai-register',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'effectiveness-verification-due',
        type: 'item',
        label: 'Effectiveness Due',
        icon: Clock,
        moduleId: 'effectiveness-verification-due',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'welder-register',
        type: 'item',
        label: 'Welder Register',
        icon: Users,
        moduleId: 'welder-register',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'wpq-expiry-dashboard',
        type: 'item',
        label: 'WPQ Expiry',
        icon: AlertTriangle,
        moduleId: 'wpq-expiry-dashboard',
        requiredCards: ['qualicheck'],
      },
      {
        id: 'iso9001-register',
        type: 'item',
        label: 'ISO 9001 Register',
        icon: FileText,
        moduleId: 'iso9001-register',
        requiredCards: ['qualicheck'],
      },
      // α-d-2 · Q-LOCK-6b · Trident QC Reports sub-group
      {
        id: 'trident-qc-reports-group',
        type: 'group',
        label: 'Trident QC Reports',
        icon: Layers,
        children: [
          {
            id: 'rinsp-report-page',
            type: 'item',
            label: 'Receiving Inspection Report',
            icon: ClipboardCheck,
            moduleId: 'rinsp-report-page',
            requiredCards: ['qualicheck'],
            keyboard: 'q r',
          },
          {
            id: 'qc-godown-summary',
            type: 'item',
            label: 'QC Godown Summary',
            icon: Layers,
            moduleId: 'qc-godown-summary',
            requiredCards: ['qualicheck'],
            keyboard: 'q g',
          },
          {
            id: 'qc-transfer-reg',
            type: 'item',
            label: 'QC Transfer Register',
            icon: ListChecks,
            moduleId: 'qc-transfer-reg',
            requiredCards: ['qualicheck'],
            keyboard: 'q t',
          },
          {
            id: 'qc-stk-trnsfer',
            type: 'item',
            label: 'QC Stock Transfer',
            icon: Layers,
            moduleId: 'qc-stk-trnsfer',
            requiredCards: ['qualicheck'],
            keyboard: 'q d',
          },
          {
            id: 'stk-iqc-st-remarks',
            type: 'item',
            label: 'QC Stock Remarks',
            icon: FileText,
            moduleId: 'stk-iqc-st-remarks',
            requiredCards: ['qualicheck'],
            keyboard: 'q b',
          },
          {
            id: 'qc-rejection-analysis',
            type: 'item',
            label: 'Rejection Analysis',
            icon: AlertOctagon,
            moduleId: 'qc-rejection-analysis',
            requiredCards: ['qualicheck'],
            keyboard: 'q a',
          },
          {
            id: 'fg-receiving-inspection',
            type: 'item',
            label: 'FG Receiving Inspection',
            icon: ShieldCheck,
            moduleId: 'fg-receiving-inspection',
            requiredCards: ['qualicheck'],
            keyboard: 'q o',
          },
          {
            id: 'reprocess-report',
            type: 'item',
            label: 'Reprocess Report',
            icon: Wrench,
            moduleId: 'reprocess-report',
            requiredCards: ['qualicheck'],
            keyboard: 'q e',
          },
        ],
      },
    ],
  },
];
